import { useEffect, useMemo, useState, type ReactNode } from "react";
import { AnalyticsHeader } from "./AnalyticsHeader";
import type { Vehicle } from "./types";
import { STATUSES } from "./types";

// Adaptado del módulo original. Solo esta copia utiliza los registros de Dataverse.
export function AnalyticsDashboard({vehicles,date,until,close,openRefusal}:{vehicles:Vehicle[];date:string;until:string;close:()=>void;openRefusal:(from:string,to:string)=>void}) {
  const [from,setFrom]=useState(date),[to,setTo]=useState(until);
  const [now,setNow]=useState(new Date());
  const [history,setHistory]=useState(false);
  const [mode,setMode]=useState<"day"|"week"|"month">("day");
  useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);
  const rows=useMemo(()=>vehicles.filter(v=>(!from||v.dispatchDate>=from)&&(!to||v.dispatchDate<=to)),[vehicles,from,to]);
  const clients=rows.reduce((n,v)=>n+v.customers,0),visited=rows.reduce((n,v)=>n+v.visited,0);
  const avance=percent(visited,clients),finished=rows.filter(v=>v.status==="Finalizado").length;
  const delayed=rows.filter(v=>isDelayed(v,now)).length;
  const durations=rows.map(v=>elapsed(v,now)).filter((n):n is number=>n!==null);
  const average=durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length):null;
  const boxes=rows.reduce((n,v)=>n+v.boxes,0),hl=rows.reduce((n,v)=>n+v.hl,0);
  const groups=useMemo(()=>{
    const map=new Map<string,Vehicle[]>();
    for(const v of vehicles){if(!v.dispatchDate)continue;let key=v.dispatchDate;if(mode==="month")key=key.slice(0,7);if(mode==="week"){const d=new Date(`${key}T12:00:00`);d.setDate(d.getDate()-((d.getDay()+6)%7));key=d.toISOString().slice(0,10)}map.set(key,[...(map.get(key)||[]),v])}
    return [...map].sort(([a],[b])=>b.localeCompare(a)).map(([key,list])=>({key,routes:list.length,clients:list.reduce((n,v)=>n+v.customers,0),visited:list.reduce((n,v)=>n+v.visited,0),boxes:list.reduce((n,v)=>n+v.boxes,0)}));
  },[vehicles,mode]);
  return <main className="min-h-screen bg-[radial-gradient(ellipse_at_top_left,#e8f0ff,transparent_55%),radial-gradient(ellipse_at_top_right,#dcf3ed,transparent_55%)] bg-[#f4f7fb] font-[Inter,Segoe_UI,Arial,sans-serif] text-slate-900 [&_p]:m-0 [&_h1]:m-0 [&_h2]:m-0">
    <AnalyticsHeader active="seguimiento" from={from} to={to} setFrom={setFrom} setTo={setTo} close={close} history={()=>setHistory(true)} switchView={openRefusal}/>
    <section className="mx-auto max-w-[1280px] px-6 py-8"><div className="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Summary kind="truck" label="Vehículos" value={rows.length} detail="Rutas del período"/><Summary kind="users" label="Clientes" value={`${visited}/${clients}`} detail={`${format(avance)} visitados`}/><Summary kind="alert" label="Retrasados" value={delayed} detail={`${format(percent(delayed,rows.length))} de rutas`}/><Summary kind="box" label="Cajas" value={Math.round(boxes).toLocaleString('es-CO')} detail={`${hl.toLocaleString('es-CO',{maximumFractionDigits:1})} HL`}/><Summary kind="clock" label="Tiempo prom." value={clock(average)} detail="Promedio de rutas"/></div>
      <div className="grid gap-5 lg:grid-cols-[1fr_1.1fr]"><Panel title="Avance global" kind="route"><div className="flex flex-col items-center gap-5 md:flex-row md:justify-center"><Gauge value={avance}/><div className="w-full max-w-xs space-y-4"><ProgressLine label="Visitas" value={avance} color="bg-[#0f7c58]" detail={`${visited}/${clients} clientes`}/><ProgressLine label="Rutas finalizadas" value={percent(finished,rows.length)} color="bg-emerald-500" detail={`${finished}/${rows.length} rutas`}/><ProgressLine label="Rutas con retraso" value={percent(delayed,rows.length)} color="bg-red-500" detail={`${delayed}/${rows.length} rutas`}/><p className="text-xs leading-5 text-slate-500">Retraso calculado por ritmo planeado por cliente. Sin hora de salida no se calcula el avance esperado.</p></div></div></Panel><Panel title="Estado de flota" kind="truck"><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{STATUSES.map(status=><StatusTile key={status} label={status} count={rows.filter(v=>v.status===status).length}/>)}<StatusTile label="Retraso" count={delayed}/></div></Panel></div>
      <section className="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between gap-3 border-b border-slate-200 px-4 py-3"><div className="flex items-center gap-2"><Glyph kind="chart"/><div><h2 className="text-sm font-semibold text-[#10223d]">Detalle por vehículo</h2><p className="text-[11px] leading-5 text-slate-500">Comparación de avance contra el ritmo planeado por cliente.</p></div></div><span className="rounded-md border border-cyan-100 bg-cyan-50 px-2 py-1 text-xs font-semibold text-[#07556b]">{rows.length} rutas</span></header><div className="max-h-[650px] overflow-auto"><table className="w-full min-w-[850px] table-fixed border-collapse text-xs"><thead className="sticky top-0 bg-gradient-to-r from-[#10223d] via-[#173e75] to-[#1264ff] text-left text-[10px] uppercase tracking-wider text-white"><tr>{['Vehículo / DT','Responsable','Visitas','Avance','Esperado','Estado'].map(label=><th className="px-3 py-2.5" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(v=>{const p=percent(v.visited,v.customers),expected=planned(v,now),behind=isDelayed(v,now);return <tr key={v.key} className={`border-b border-slate-100 ${behind?'bg-red-50/60':'even:bg-slate-50/60'}`}><td className="px-3 py-3"><div className="flex items-center gap-2"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-md ${behind?'bg-red-100 text-red-600':'bg-[#e9f3ff] text-[#10223d]'}`}><Glyph kind={behind?'alert':'truck'}/></span><div><b className="block text-[#10223d]">{v.plate}</b><small className="text-slate-500">{v.dt}</small></div></div></td><td className="truncate px-3 py-3 text-slate-600" title={v.responsible}>{v.responsible||'Sin responsable'}</td><td className="px-3 py-3 font-semibold text-[#10223d]">{v.visited} / {v.customers}</td><td className="px-3 py-3"><div className="flex items-center gap-2"><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-200"><div className={`h-full rounded-full ${behind?'bg-gradient-to-r from-red-500 to-orange-400':'bg-gradient-to-r from-[#0f7c58] to-[#00b8d9]'}`} style={{width:`${p}%`}}/></div><b className={behind?'text-red-600':'text-[#10223d]'}>{format(p)}</b></div></td><td className="px-3 py-3 text-slate-500">{expected===null?'Sin plan':format(expected)}</td><td className="px-3 py-3"><span className={`inline-block rounded-md border px-2 py-1 text-[10px] font-semibold ${tone(behind?'Retraso':v.status)}`}>{behind?'Retraso':v.status}</span></td></tr>})}{!rows.length&&<tr><td colSpan={6} className="px-4 py-12 text-center text-slate-500">No hay rutas para el período seleccionado.</td></tr>}</tbody></table></div></section>
    </section>
    {history&&<div className="fixed inset-0 z-[130] grid place-items-center bg-[#10223d]/50 p-4 backdrop-blur-sm" onClick={()=>setHistory(false)}><section role="dialog" aria-label="Histórico de seguimiento" className="max-h-[85vh] w-full max-w-5xl overflow-auto rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><header className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#0f7c58]">Analítica histórica</p><h2 className="text-xl font-semibold text-[#10223d]">Evolución del seguimiento</h2></div><button aria-label="Cerrar histórico" className="grid h-9 w-9 place-items-center rounded-md border-0 bg-slate-50 text-xl" onClick={()=>setHistory(false)}>×</button></header><div className="mb-5 inline-flex rounded-lg bg-slate-100 p-1">{(['day','week','month'] as const).map((item,i)=><button key={item} className={`rounded-md border-0 px-4 py-2 text-sm font-semibold ${mode===item?'bg-[#10223d] text-white':'bg-transparent text-slate-600'}`} onClick={()=>setMode(item)}>{['Día','Semana','Mes'][i]}</button>)}</div><div className="space-y-4">{groups.map(g=><div className="rounded-lg border border-slate-200 p-4" key={g.key}><div className="mb-3 flex items-center justify-between"><b className="text-sm text-[#10223d]">{mode==='week'?'Semana del ':''}{g.key}</b><span className="text-xs text-slate-500">{g.routes} rutas · {g.visited}/{g.clients} clientes · {Math.round(g.boxes)} cajas</span></div><ProgressLine label="Avance" value={percent(g.visited,g.clients)} color="bg-[#1264ff]"/></div>)}{!groups.length&&<p className="py-8 text-center text-slate-500">No hay registros históricos.</p>}</div></section></div>}
  </main>;
}

function Summary({kind,label,value,detail}:{kind:string;label:string;value:ReactNode;detail:string}){return <div className="rounded-lg border border-slate-200 bg-gradient-to-br from-white to-slate-50/60 p-5 shadow-[0_8px_24px_rgba(15,23,42,.04)]"><div className="mb-4 flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-md bg-gradient-to-br from-[#10223d] to-[#1264ff] text-white shadow-lg shadow-blue-500/20"><Glyph kind={kind}/></span><span className="h-2.5 w-2.5 rounded-full bg-[#11a36a]"/></div><p className="text-sm font-medium text-slate-500">{label}</p><p className="text-3xl font-semibold leading-10 text-[#10223d]">{value}</p><p className="text-sm text-slate-500">{detail}</p></div>}
function Panel({title,kind,children}:{title:string;kind:string;children:ReactNode}){return <section className="rounded-lg border border-slate-200 bg-white/95 p-5 shadow-[0_10px_30px_rgba(15,23,42,.04)]"><div className="mb-5 flex items-center gap-2 text-[#10223d]"><Glyph kind={kind}/><h2 className="text-lg font-semibold">{title}</h2></div>{children}</section>}
function Gauge({value}:{value:number}){const radius=42,circumference=2*Math.PI*radius,offset=circumference-(value/100)*circumference;return <div className="relative grid h-48 w-48 shrink-0 place-items-center"><svg aria-hidden="true" className="h-full w-full -rotate-90" viewBox="0 0 110 110"><defs><linearGradient id="gaugeGradient" x1="0" x2="1" y1="0" y2="1"><stop offset="0%" stopColor="#1264ff"/><stop offset="55%" stopColor="#00b8d9"/><stop offset="100%" stopColor="#0f7c58"/></linearGradient></defs><circle cx="55" cy="55" r={radius} fill="none" stroke="#e2e8f0" strokeWidth="11"/><circle cx="55" cy="55" r={radius} fill="none" stroke="url(#gaugeGradient)" strokeDasharray={circumference} strokeDashoffset={offset} strokeLinecap="round" strokeWidth="11" className="drop-shadow-sm"/></svg><div className="absolute text-center"><p className="text-4xl font-semibold text-[#10223d]">{format(value)}</p><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Global</p></div></div>}
function ProgressLine({label,value,color,detail}:{label:string;value:number;color:string;detail?:string}){return <div><div className="mb-2 flex justify-between gap-2 text-xs"><span className="font-medium text-slate-600">{label}</span><span className="font-semibold text-[#10223d]">{detail?`${detail} · `:''}{format(value)}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className={`h-2 rounded-full ${color}`} style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div></div>}
function StatusTile({label,count}:{label:string;count:number}){return <div className={`rounded-md border px-3 py-2.5 ${tone(label)}`}><p className="truncate text-xs font-semibold">{label}</p><p className="text-2xl font-semibold leading-9">{count}</p></div>}
function tone(status:string){if(status==='Retraso')return 'bg-red-50 text-red-700 border-red-100';if(status==='Finalizado')return 'bg-emerald-50 text-emerald-700 border-emerald-100';if(status==='En ruta')return 'bg-emerald-50 text-emerald-700 border-emerald-100';if(status==='Cargando')return 'bg-amber-50 text-amber-700 border-amber-100';if(status==='Retornando')return 'bg-indigo-50 text-indigo-700 border-indigo-100';if(status==='Pernoctado')return 'bg-violet-50 text-violet-700 border-violet-100';if(status==='Cambio de fecha')return 'bg-orange-50 text-orange-700 border-orange-100';return 'bg-slate-50 text-slate-700 border-slate-200'}
function percent(value:number,total:number){return total?Math.min(100,Math.round(value/total*1000)/10):0}
function format(value:number){return `${value.toFixed(1)}%`}
function seconds(value:string){const m=value?.match(/(\d{1,2}):(\d{2})(?::(\d{2}))?/);return m?Number(m[1])*3600+Number(m[2])*60+Number(m[3]||0):null}
function elapsed(v:Vehicle,now:Date){const start=seconds(v.departureTime);if(start===null)return null;const end=seconds(v.arrivalTime)??(now.getHours()*3600+now.getMinutes()*60+now.getSeconds());return (end-start+86400)%86400}
function planned(v:Vehicle,now:Date){const duration=seconds(v.plannedTime),time=elapsed(v,now);return duration&&time!==null?Math.min(100,time/duration*100):null}
function isDelayed(v:Vehicle,now:Date){const expected=planned(v,now);return expected!==null&&percent(v.visited,v.customers)+1<expected}
function clock(value:number|null){return value===null?'Pendiente':`${String(Math.floor(value/3600)).padStart(2,'0')}:${String(Math.floor(value%3600/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}
function Glyph({kind}:{kind:string}){const paths:Record<string,ReactNode>={back:<path d="m14 6-6 6 6 6M8 12h12"/>,chart:<path d="M4 20V10m6 10V4m6 16v-7m4 7H2"/>,truck:<><path d="M3 6h11v10H3zM14 10h4l3 3v3h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,alert:<><path d="m12 3 10 18H2zM12 9v4"/><path d="M12 17h.01"/></>,box:<><path d="m3 6 9-4 9 4v12l-9 4-9-4zM3 6l9 4 9-4M12 10v12"/></>,users:<><circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M17 4a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 5v2"/></>,route:<path d="M4 5h10a5 5 0 0 1 0 10H8a3 3 0 0 0 0 6h12M4 3v4M20 19v4"/>};return <svg aria-hidden="true" className="h-5 w-5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[kind]||paths.chart}</svg>}
