type Props = { active: 'seguimiento' | 'refusal'; from: string; to: string; setFrom: (value:string)=>void; setTo: (value:string)=>void; close:()=>void; history:()=>void; switchView:(from:string,to:string)=>void; checkin?:()=>void };

export function AnalyticsHeader({active,from,to,setFrom,setTo,close,history,switchView,checkin}:Props){
  return <header className="sticky top-0 z-20 border-b border-white/70 bg-white/85 shadow-sm backdrop-blur-xl"><div className="mx-auto flex max-w-[1280px] flex-col gap-4 px-6 py-4 xl:flex-row xl:items-center xl:justify-between">
    <div className="flex items-center gap-3"><button aria-label="Volver a seguimiento" onClick={close} className="grid h-10 w-10 shrink-0 place-items-center rounded-md border-0 bg-transparent text-xl text-[#10223d] hover:bg-slate-100">←</button><div><p className="m-0 text-xs font-semibold uppercase tracking-[.18em] text-[#008b6a]">Analítica diaria</p><h1 className="m-0 text-2xl font-semibold leading-tight text-[#10223d]">Seguimiento Logísticos</h1></div></div>
    <div className="flex flex-wrap items-center gap-2"><div className="grid gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 shadow-sm">{(['Desde','Hasta'] as const).map((label,i)=><label key={label} className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-slate-500"><span aria-hidden="true">▦</span>{label}<input aria-label={`${label} analítica`} className="h-6 w-[145px] border-0 bg-transparent text-xs font-semibold text-[#10223d]" type="date" value={i?to:from} min={i?from||undefined:undefined} max={i?undefined:to||undefined} onChange={e=>i?setTo(e.target.value):setFrom(e.target.value)}/></label>)}</div>
    <button onClick={history} className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm font-semibold text-[#10223d] shadow-sm hover:bg-slate-50">Histórico</button>
    <nav aria-label="Vistas de analítica" className="flex items-center gap-1 rounded-lg border border-slate-200 bg-white p-1 shadow-sm">{(['seguimiento','refusal'] as const).map(view=><button key={view} aria-current={active===view?'page':undefined} onClick={()=>active!==view&&switchView(from,to)} className={`inline-flex h-8 items-center gap-2 rounded-md border-0 px-3 text-sm font-semibold transition ${active===view?'bg-gradient-to-r from-[#10223d] to-[#1264ff] text-white shadow-sm':'bg-transparent text-slate-600 hover:bg-slate-50 hover:text-[#10223d]'}`}><span aria-hidden="true">{view==='seguimiento'?'▥':'♧'}</span>{view==='seguimiento'?'Seguimiento':'Refusal'}</button>)}</nav>
    {checkin&&<button onClick={checkin} className="h-10 rounded-md border border-amber-200 bg-amber-50 px-3 text-xs font-semibold text-amber-800 hover:bg-amber-100">Cajas check-in</button>}</div>
  </div></header>;
}
