import { strict as assert } from 'node:assert';
import { refusalBoxes, refusalSummary, refusalHistory } from '../src/refusalModel.ts';
import type { Vehicle } from '../src/types';
const vehicle={key:'a',dt:'123',plate:'ABC123',dispatchDate:'2026-09-12',boxes:100,customers:1,visited:0,hl:0,responsible:'',territory:'',departureTime:'',arrivalTime:'',plannedTime:'',status:'Cargando'} as Vehicle;
assert.equal(refusalBoxes(vehicle),null);
assert.equal(refusalBoxes({...vehicle,modulatedBoxes:10}),null);
assert.equal(refusalBoxes({...vehicle,modulatedBoxes:10,managedBoxes:4}),6);
assert.equal(refusalBoxes({...vehicle,modulatedBoxes:10,managedBoxes:4,checkinBoxes:0}),0);
assert.equal(refusalBoxes({...vehicle,checkinBoxes:NaN}),null);
assert.equal(refusalBoxes({...vehicle,checkinBoxes:-2}),null);
assert.equal(refusalBoxes({...vehicle,modulatedBoxes:2,managedBoxes:4}),0);
assert.equal(refusalSummary([vehicle]).percentage,null);
assert.equal(refusalSummary([]).limit,0);
const partial=refusalSummary([vehicle,{...vehicle,key:'b',checkinBoxes:2}]);
assert.equal(partial.complete,false);
assert.equal(partial.percentage,1);
assert.equal(partial.known,1);
assert.equal(refusalSummary([{...vehicle,checkinBoxes:0}]).complete,true);
assert.equal(refusalHistory([vehicle,{...vehicle,key:'b',dispatchDate:'2026-09-13'}],'week')[0].key,'2026-09-07');
assert.equal(refusalHistory([vehicle,{...vehicle,key:'b',dispatchDate:'2026-09-14'}],'week').length,2);
assert.equal(refusalHistory([vehicle],'month')[0].key,'2026-09');
console.log('Refusal: 16 verificaciones correctas.');
